name: Deploy Simple HTML to Subdomain

on:
  push:
    branches:
      - main # Ubah ke 'master' jika default branch Anda menggunakan master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to hPanel Subdomain via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          SOURCE: "./" 
          TARGET: "~/domains/elfaraby.com/public_html/test-cicd/"
          ARGS: "-rltgoDzvO --delete"